language: rust

rust:
  - stable

cache: cargo

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt --all -- --check
  - cargo check --all
  - cargo build --all
  - cargo test --all
  - cargo build --features "liquid" --all
